### ISSUE TITLE
Use undo-redo

### ISSUE THREAD

**Issue by Haider-Mirza** [devraza/dianciemacs#2]
Instead of using 'undo-fu', you can just make evil use the undo-redo function that is inbuilt into Emacs 28. 

Nobody wants excessive packages being loaded.

**Comment by devraza** [comment]
Not sure why I've decided to use `undo-fu` instead of `undo-redo`, but I'm sure I tried out both before settling with `undo-fu`.

I try not to use unnecessary packages, but in order to establish required functionality it's not a problem.
